title: Kaung Htet Htun
description: > #You cannot create experience. You must undergo it.
permalink: ':title/'
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#url: "https://kogyikaunghtet.ubuntu-mm.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

author: Kaung Htet Htun
author-img: khh.jpg 
about-author: I am an embedded hardware enthusiast. Always hungry to keep learning.
social-twitter:
social-facebook: kaung2013
social-github: kogyikaunghtet
social-linkedin: kogyikaunghtet
social-email: kogyikaunghtet@gmail.com

# Disqus
discus-identifier: https-kogyikaunghtet-github-io

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
